#!/bin/sh

cordova clean
cordova prepare android
cordova build --release android
/home/aureliosaraiva/jdk/bin/jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore livrio-production.keystore -keypass Z4vMkyltu -storepass Z4vMkyltu platforms/android/build/outputs/apk/android-release-unsigned.apk livrio
rm -f Livrio.apk

/home/aureliosaraiva/android-sdk-linux/build-tools/23.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-unsigned.apk Livrio.apk


#keytool -exportcert -alias livrio -keystore livrio-production.keystore | openssl sha1 -binary | openssl base64
#keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

#./device
